AWSTemplateFormatVersion: 2010-09-09
Description: |
  Kaarstthenn - Dynamo Tables

Parameters:
  ProjectName:
    Type: String
    Description: Application name
  ENV:
    Type: String
    Description: ENV
  MN:
    Type: String
    Description: MN

Resources:
  DataTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub ${ProjectName}-${ENV}-DY-${MN}-Data
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoDBTable:
    Description: DynamoDBTable Name
    Value: !Sub ${ProjectName}-${ENV}-DY-${MN}-Data
  DynamoDBTableARN:
    Description: DynamoDBTable arn
    Value: !GetAtt DataTable.Arn